# Generated by Django 3.1.5 on 2021-05-02 15:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_keywords', models.TextField(blank=True, max_length=1000, null=True)),
                ('category_description', models.CharField(blank=True, max_length=160, null=True)),
                ('category_author', models.CharField(blank=True, max_length=160, null=True)),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorymodel',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
                ('status', models.CharField(blank=True, default='Unread', max_length=20, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationmodel',
            },
        ),
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_keywords', models.TextField(blank=True, max_length=1000, null=True)),
                ('artilce_meta_des', models.CharField(blank=True, max_length=160, null=True)),
                ('article_author', models.CharField(blank=True, max_length=100, null=True)),
                ('article_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article_image', models.ImageField(blank=True, null=True, unique=True, upload_to='ArticlesImages')),
                ('article_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.categorymodel', verbose_name='category')),
            ],
            options={
                'db_table': 'articlesmodel',
            },
        ),
    ]
