# Generated by Django 3.1.5 on 2021-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactusmodel',
            },
        ),
    ]
